# Docker Compose for local development and testing
version: '3.8'

services:
  # Flask Application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - SESSION_SECRET=dev-secret-key-change-in-production
      - FLASK_ENV=development
      - WEB_CONCURRENCY=2
      - DATABASE_URL=sqlite:///mediafusion.db
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./static/subtitles:/app/static/subtitles
      - ./static/vpn:/app/static/vpn
      - ./mediafusion.db:/app/mediafusion.db
    depends_on:
      - openvpn
    networks:
      - app-network
    restart: unless-stopped

  # OpenVPN Server (requires privileged mode)
  openvpn:
    image: kylemanna/openvpn:latest
    container_name: openvpn-server
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./openvpn-data:/etc/openvpn
    networks:
      - app-network
    restart: unless-stopped
    # Note: First time setup required - see RENDER_DEPLOY.md

networks:
  app-network:
    driver: bridge

volumes:
  openvpn-data:
