# Render Blueprint Configuration
# This file defines infrastructure as code for Render.com

services:
  # Main Flask Web Service
  - type: web
    name: stream-weaver
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter  # Change to 'standard' or 'pro' for better performance
    region: oregon  # or 'frankfurt', 'singapore', 'ohio'
    branch: main
    
    # Auto-deploy on git push
    autoDeploy: true
    
    # Health check endpoint
    healthCheckPath: /health
    
    # Environment variables
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      
      - key: SESSION_SECRET
        generateValue: true  # Auto-generate secure secret
      
      - key: FLASK_ENV
        value: production
      
      - key: WEB_CONCURRENCY
        value: 4  # Number of gunicorn workers
      
      # Database connection (if using Render PostgreSQL)
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: stream-weaver-db
      #     property: connectionString
      
      # Max file sizes (in bytes)
      - key: MAX_FILE_SIZE
        value: 104857600  # 100MB
      
      - key: MAX_SUBTITLE_SIZE
        value: 5242880  # 5MB

# Optional: PostgreSQL Database
# Uncomment if you want to use PostgreSQL instead of SQLite
# databases:
#   - name: stream-weaver-db
#     databaseName: streamweaver
#     user: streamweaver
#     plan: free  # or 'starter', 'standard', 'pro'
#     region: oregon
#     ipAllowList: []  # Empty allows all Render services

# Optional: Redis for caching (paid plans)
# - type: redis
#   name: stream-weaver-cache
#   plan: free
#   region: oregon
